
import { Inter } from "next/font/google";
import "./globals.css";
import Geolocation from "../components/Geolocation"; 
import { UserLocationContext, UserLocationProvider } from "@/context/UserLocationContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Jatri",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserLocationProvider> 
          {children}
          <Geolocation />
        </UserLocationProvider> 
      </body>
    </html>
  );
}
